### ISSUE TITLE
Windows build not configured properly

### ISSUE THREAD

**Issue by sdirkse67** [DrTimothyAldenDavis/SuiteSparse#315] opened 2023-05-04 19:39 UTC
When I do a build on Windows, there is some confusion between the Debug and Release builds.  As a result, things do not work properly.

I get this when doing a local build, and the issue shows already with SuiteSparse_Config (both with the stable 7.0.1 and with master).  I run this:

```
cd SuiteSparse_config/build
cmake -DNFORTRAN=ON -DLOCAL_INSTALL=1 .. && cmake --build .
```
and the results (in the attached file) show that only the Debug version is built, but eventually the Release version will be copied, hence the failure.

[cmake.txt](https://github.com/DrTimothyAldenDavis/SuiteSparse/files/11400933/cmake.txt)

Playing around a little, I notice that if I run instead   `cmake --build . --config Release` then the Release version is built.

**Comment by mmuetzel** [comment] 2023-05-16 14:36
I'm guessing your CMake defaults to a multi-config generator.
In case it does, isn't the behavior that you are describing expected?

**Comment by sdirkse67** [comment] 2023-05-16 21:03
The config/build system is building only the Debug version, but during the install it is attempting to copy only the Release version.  I do not consider this expected behavior, whether CMake defaults to a multi-config generator or not.

**Comment by mmuetzel** [comment] 2023-05-17 06:26
Is SuiteSparse the only project that shows that behavior for you?
Afaict, SuiteSparse doesn't mess with the multi-config settings between building and installation. Maybe, that's an issue in CMake itself?
Do you know which generator your cmake defaults to?

**Comment by DrTimothyAldenDavis** [comment] 2023-06-12 14:07
The SuiteSparsePolicy.cmake script checks if CMAKE_BUILD_TYPE is set, and if not, sets it to Release.  See:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/36f873d57d20f96b26e945f79ebfab420ecce836/SuiteSparse_config/cmake_modules/SuiteSparsePolicy.cmake#L183

Can you try the recent update to the dev version?

The cmake script you attach above shows that the script reports the build type is Release so I'm not sure why Debug appears later on.

I'll see if I can replicate this in Windows.  I rarely use Windows so things like this can slip by the tests.

**Comment by sdirkse67** [comment] 2023-06-12 16:18
I tried the latest dev version (pulled earlier today): no change in behavior.

I make no claims to CMake expertise, but a web search suggests that it is necessary to specify the config to build in the build command.  That is consistent with my experience here.  Running

`cmake --build .`

builds the Debug version but running

`cmake --build . --config Release`

builds the release version.

https://stackoverflow.com/questions/19024259/how-to-change-the-build-type-to-release-mode-in-cmake

> For multi-config generators like the Visual Studio generators and "Ninja Multi-Config", the config to build is specified in the build command using [the --config argument](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-build-config) argument like --config Release. Since CMake 3.17, A default value can currently be specified at configure time for the Ninja Multi-Config generator by setting the value of [the CMAKE_DEFAULT_BUILD_TYPE variable](https://cmake.org/cmake/help/latest/variable/CMAKE_DEFAULT_BUILD_TYPE.html), which will be used if the --config argument isn't passed to the build command. At the current time, a default cannot be set for Visual Studio generators.

**Comment by sdirkse67** [comment] 2023-06-12 18:10
I did some googling, some doc reading, some colleague-checking, and some experimenting.  Everything I see is consistent with these conclusions:

1. CMAKE_BUILD_TYPE is useful for Makefile- or Ninja-based generators, but it is ignored for Visual Studio-based generators.
2. For Visual Studio generators, the build type is specified with the build command, i.e.  `cmake --build . --config Release`

**Comment by DrTimothyAldenDavis** [comment] 2023-06-12 18:35
Got it -- thanks.  So for Visual Studio, the expectation is that the one installing the package will always add the `--config Release` or `--config Debug` flag to their command?

**Comment by sdirkse67** [comment] 2023-06-12 18:48
I would say that `--config Release` or `--config Debug` should be included with the `cmake --build .` when using VS.  IIRC, the install command was assuming that it was the Release build getting installed, but that Release build wasn't there: VS had built a Debug version.

**Comment by DrTimothyAldenDavis** [comment] 2023-06-12 19:10
Thanks.  I'll add that to the top-level README, something like:

```
For Windows, import each `*/CMakeLists.txt` file into MS Visual Studio.
A single top-level CMake script is being considered as a feature in the
future.  Be sure to specify the build type as Release; for example, to
build `SuiteSparse_config` on Windows in the command window:

    cd SuiteSparse_config/build
    cmake ..
    cmke --build . --config Release

```

**Comment by sdirkse67** [comment] 2023-06-12 19:39
In my case I am running everything from the command line.  For example I run

```
export CMAKE_OPTIONS="-DNFORTRAN=ON"
( cd SuiteSparse_config && make local )
```
and the rest is controlled by the Makefile in the SuiteSparse_config directory.  I was hoping that the Makefile (just there for convenience) could be adjusted to be even more convenient.  Perhaps I should do the change and make a pull request?

**Comment by DrTimothyAldenDavis** [comment] 2023-06-12 21:34
I see.  I didn't realize you were using the top-level Makefiles for each package (I don't use Windows much, except to check the port of SuiteSparse, but I thought using "make" on Windows was either rare or not possible).

**Comment by sdirkse67** [comment] 2023-06-13 16:49
I've started a branch to update the top-level Makefiles (e.g. SuiteSparse_config/Makefile), but before I finish it up I'm checking if you would accept it.  The whole situation seems a little odd: why is it necessary to specify --config Release for the build but not for the install?  Also, if using make on Windows is rare (I believe it is) then adding more to the Makefiles for this small group of users may not be desired.

In any case, I'll attach the new Makefile and a diff from the previous one, and I'll await positive word before continuing.

[Makefile.txt](https://github.com/DrTimothyAldenDavis/SuiteSparse/files/11737269/Makefile.txt)
[diff.txt](https://github.com/DrTimothyAldenDavis/SuiteSparse/files/11737276/diff.txt)

**Comment by DrTimothyAldenDavis** [comment] 2023-06-13 18:47
Yes, I'd like to do something like this, but simpler. I thought I would just add "--config Release" to every default target. I already have a "make debug" option, at least in some Makefiles. That uses --config Debug. 

(Also, I would need a signed CLA for a PR. If that's a problem then I can write the update.

**Comment by sdirkse67** [comment] 2023-06-13 19:32
I think I'll let you do this.  I'm a cmake newbie, so I cannot speak to the risks/rewards of putting this on all make users.

I would be happy to test your changes, either in a MR or after you push them to master.

**Comment by DrTimothyAldenDavis** [comment] 2023-06-14 15:06
Thanks -- having you test it would be great because our current tests on github don't use make on Windows.  I'll take a stab at this in the next few days and post an update on the dev2 branch for you to try.

**Comment by DrTimothyAldenDavis** [comment] 2023-06-14 23:47
I've just posted an update to both the dev and the dev2 branches. Can you give it a try?

**Comment by sdirkse67** [comment] 2023-06-15 20:42
Short version: the addition of `--config Release` in 410b5f2277 is a positive change for me, with no detected negatives.

Longer version: I can do what I really want to do much better now:
```
PKG="SuiteSparse_config AMD CAMD CCOLAMD COLAMD CHOLMOD UMFPACK"
for pkg in $PKG ; do
    ( cd $pkg && make local && make install ) 
done
```

Testing further, I found I could not build GraphBLAS, but that failure seems unrelated to 410b5f2277.  The log output is below.

```
[nb@kermit ~/sdirkse/github/SuiteSparse/master]$ ( cd GraphBLAS && make local && make install )
( cd build && cmake  -DLOCAL_INSTALL=1 .. && cmake --build . --config Release -j8 )
-- Building SuiteSparse:GraphBLAS version: v8.0.2, date: June 16, 2023
-- GraphBLAS C API: v2.0, date: Nov 15, 2021
-- Source:        C:/home/nb/sdirkse/github/SuiteSparse/master/GraphBLAS
-- Build:         C:/home/nb/sdirkse/github/SuiteSparse/master/GraphBLAS/build
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.20348.
-- Install lib:     C:/home/nb/sdirkse/github/SuiteSparse/master/lib
-- Install include: C:/home/nb/sdirkse/github/SuiteSparse/master/include
-- Install bin:     C:/home/nb/sdirkse/github/SuiteSparse/master/bin
-- Install rpath:   C:/home/nb/sdirkse/github/SuiteSparse/master/lib
-- Build   rpath:   C:/home/nb/sdirkse/github/SuiteSparse/master/GraphBLAS/build;C:/home/nb/sdirkse/github/SuiteSparse/master/lib
-- Build type:    Release
-- Fortran: not available
-- CUDA: not enabled
-- getenv("HOME"): available
-- GraphBLAS CPU JIT: enabled
-- GraphBLAS CUDA JIT: disabled
-- cpu_features (by google.com): enabled 
-- Building dynamic GraphBLAS library
-- ANSI C11 atomics: OK. -latomic not needed
-- CMAKE OpenMP libraries:    
-- CMAKE OpenMP include:
-- CMAKE OpenMP C flags:      -openmp
-- CMAKE C flags: /DWIN32 /D_WINDOWS /O2 -wd"4244" -wd"4146" -wd"4018" -wd"4996" -wd"4047" -wd"4554" /O2 /Ob2 /DNDEBUG -openmp
-- Skipping the demos in GraphBLAS/Demo
-- ------------------------------------------------------------------------
-- JIT configuration:
-- ------------------------------------------------------------------------
-- JIT C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe
-- JIT C flags:    /DWIN32 /D_WINDOWS /O2 -wd\"4244\" -wd\"4146\" -wd\"4018\" -wd\"4996\" -wd\"4047\" -wd\"4554\" /O2 /Ob2 /DNDEBUG -openmp        
-- JIT link flags: /machine:x64
-- JIT lib prefix:
-- JIT lib suffix: .dll
-- JIT obj suffix: .obj
-- JIT cache:      C:\home\nb/.SuiteSparse/GrB8.0.2
-- JIT openmp inc:
-- JIT openmp dirs
-- JIT libraries:
-- JIT cmake libs:
-- ------------------------------------------------------------------------
-- SuiteSparse CMAKE report for: graphblas
-- ------------------------------------------------------------------------
-- inside common SuiteSparse root:  true
-- install in SuiteSparse/lib and SuiteSparse/include: 1
-- build type:           Release
-- NSTATIC:              true (do not build static library)
-- use OpenMP:           yes
-- C compiler:           C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x64/cl.exe
-- C flags:              /DWIN32 /D_WINDOWS /O2 -wd"4244" -wd"4146" -wd"4018" -wd"4996" -wd"4047" -wd"4554" /O2 /Ob2 /DNDEBUG -openmp
-- C++ compiler:
-- C++ flags:
-- C Flags release:      /O2 /Ob2 /DNDEBUG
-- C++ Flags release:
-- Fortran compiler:     none
-- compile definitions:  _CRT_SECURE_NO_WARNINGS
-- ------------------------------------------------------------------------
-- Configuring done (0.1s)
-- Generating done (0.2s)
-- Build files have been written to: C:/home/nb/sdirkse/github/SuiteSparse/master/GraphBLAS/build
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/home/nb/sdirkse/github/SuiteSparse/master/GraphBLAS/CMakeLists.txt
  GB_jitifyer.c
C:\home\nb\sdirkse\github\SuiteSparse\master\GraphBLAS\xxHash\xxhash.h(1177,1): fatal error C1083: Cannot open include file: 'stdalign.h': No such
 file or directory [C:\home\nb\sdirkse\github\SuiteSparse\master\GraphBLAS\build\graphblas.vcxproj]
make: *** [Makefile:35: local] Error 1
```

If you are keen to pursue this latter error I can be a guinea pig (you are owed that much and more): your choice.

**Comment by DrTimothyAldenDavis** [comment] 2023-06-16 00:04
Nuts.  That's a new one.  One more thing that MS breaks badly.  xxhash is a very portable code, but not something I wrote.

The line in question is protected by an ifdef:

```
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L) /* >= C11 */
#  include <stdalign.h>
#  define XXH_ALIGN(n)      alignas(n)
#elif defined(__cplusplus) && (__cplusplus >= 201103L) /* >= C++11 */
/* In C++ alignas() is a keyword */
#  define XXH_ALIGN(n)      alignas(n)
#elif defined(__GNUC__)
#  define XXH_ALIGN(n)      __attribute__ ((aligned(n)))
#elif defined(_MSC_VER)
#  define XXH_ALIGN(n)      __declspec(align(n))
#else
#  define XXH_ALIGN(n)   /* disabled */
#endif
```

The stdalign.h include file is part of the ANSI C11 standard, which the compiler (cl.exe) is merrily breaking.  The compiler is declaring that it complies with the ANSI C11 standard, but it doesn't.  There are other things that Microsoft's cl compiler mangles.  I wasn't aware that cl.exe declares __STDC_VERSION__ at this level. however.

What is the value of __STDC_VERSION__ used by cl.exe?

I could probably fix this with a cmake configuration step, and then revise that first test "if defined __STDC__VERSION__ ..." with "ifndef NOT_HAVE_STDALIGN_H" where that macro could be configured based on a cmake test.

**Comment by sdirkse67** [comment] 2023-06-16 03:59
This compiler has **STDC_VERSION** set to 201112.

It would be simpler to just pull up the _MSC_VER test.  For example, this compiler defines that to be 1929.  This is making an assumption about __declspec(align(n)) being available/suitable for all MSC compilers: seems reasonable to hope for this.  But safe to assume??

```
#if   defined(_MSC_VER)
#  define XXH_ALIGN(n)      __declspec(align(n))
#elif defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L) /* >= C11 */
#  include <stdalign.h>
#  define XXH_ALIGN(n)      alignas(n)
#elif defined(__cplusplus) && (__cplusplus >= 201103L) /* >= C++11 */
/* In C++ alignas() is a keyword */
#  define XXH_ALIGN(n)      alignas(n)
#elif defined(__GNUC__)
#  define XXH_ALIGN(n)      __attribute__ ((aligned(n)))
#else
#  define XXH_ALIGN(n)   /* disabled */
#endif
```

From the quick browsing of available info on stdalign.h, I'm not filled with hope that confusion around this header will get cleaned up anytime soon.

**Comment by DrTimothyAldenDavis** [comment] 2023-06-16 12:42
I only #include xxhash.h in one place, so I tried to redefined __STDC_VERSION__ just before including the xxhash.h file.  The compiler complained when I forced this on gcc on my Mac, so it might break entirely in other compilers.  I was trying not to distribute a modified version of xxhash.h, which makes it harder to upgrade in the future.  Oh well.

So I went ahead with a slight variant of your suggestion.  The downside to this is that I now have to port this hack from my modified xxhash.h to the latest version of xxhash.h.  I upgraded to the latest version from the xxHash git repo, and then made a change that is easier to migrate to a future version of xxhash.h.

See https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/333 .  Once that passes the CI, I'll include this hack in the latest SuiteSparse v7.1.0.

**Comment by DrTimothyAldenDavis** [comment] 2023-06-16 19:33
See the v7.1.0.beta1 pre-release.  This should be fixed now.

**Comment by sdirkse67** [comment] 2023-06-16 21:06
The build works all the way down to and including GraphBLAS.  I get a SPEX failure but that is expected as mentioned in the SPEX README.

**Comment by DrTimothyAldenDavis** [comment] 2023-06-16 21:31
Great -- thanks for checking it out!

**Closed as completed by DrTimothyAldenDavis** 2023-06-16 21:31 UTC

**Comment by mmuetzel** [comment] 2023-06-29 16:24
This built prior to the change from #333 with MSVC in the CI:
https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/5272757127/jobs/9535391807#step:14:6431

@sdirkse67: Which version of MSVC are you using? Afaict, the CI runs with 
```
-- The C compiler identification is MSVC 19.35.32217.1
[...]
  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.35.32215/bin/HostX64/x64/cl.exe - skipped
```

In case this is a version thing, would a version check to only fall back to non-standard code in affected versions be appropriate?

Also: Should the C++ branch of that condition tree be moved up? Most C++ compilers that support C++11 also support C11 nowadays. So, the C11 branch would be taken for those compilers.

**Comment by sdirkse67** [comment] 2023-07-03 15:40
My build of the dev branch shows this:
`
-- The C compiler identification is MSVC 19.29.30148.0
`

Your comment suggests that something does not build now, but you don't mention what that is, or provide details, so I can't suggest any fixes.

**Comment by mmuetzel** [comment] 2023-07-03 16:07
Sorry for having been unclear.

The CI still passes after these changes.

What I tried to say is: The comment suggests that MSVC is broken:
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/GraphBLAS/xxHash/xxhash.h#L1185
But the CI compiled that file with MSVC 2022 just fine also before that change. So, the comment is probably wrong. If MSVC was broken in an older version but follows the standard in a newer version, it might make sense to only fall back to the work-around for the affected versions of MSVC.

The other part just suggests to *not* include `<stdalign.h>` when it's not necessary. Again: It currently compiles. But looking at the if-else-ladder, the current behavior might not be what was intended when writing that logic:
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/GraphBLAS/xxHash/xxhash.h#L1193

Maybe, I'll just open a PR with the changes that I'm thinking of.

**Comment by mmuetzel** [comment] 2023-07-03 16:28
See: https://github.com/DrTimothyAldenDavis/GraphBLAS/pull/225
