### ISSUE TITLE
cholmod_analyze bad parallel performance, race conditions

### ISSUE THREAD

**Issue by jakub-homola** [DrTimothyAldenDavis/SuiteSparse#375] opened 2023-09-01 12:57 UTC
**Describe the bug**
Usin the function `cholmod_analyze` from multiple threads concurrently (all threads have their own common object and matrices) has very bad performance, it does not scale. Sequentially it takes around 17 seconds to analyze 64 matrices, but in parallel on 64 cores (with properly pinned threads), it takes 14 seconds.

Timing the program with `time`, it reports that the vast majority of time is spent in system calls, `htop` is all red indicating that kernel calls are being executed.

Profiling the program with arm map, I boiled down the problem to the function [gk_randint64](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/24e8e2bdddc43b98d66268b6d97f21b3229f5374/CHOLMOD/SuiteSparse_metis/GKlib/random.c#L84). It uses the stdlib's `rand` function, which is on my system protected with locks on the inside. If it was not protected, race conditions would probably occur inside the random, since it contains a single shared global state. I noticed the `USE_GKRAND` macro, but I cannot use this option either, since it again seems to have a single shared global state.

I observe this behavior when using the METIS and NESDIS ordering, AMD and COLAMD seem to be fine in this sense, but the numerical factorization then takes more time.

**To Reproduce**
See the `source.cpp` and `Makefile` in [cholmod_parallel_analysis.zip](https://github.com/DrTimothyAldenDavis/SuiteSparse/files/12497669/cholmod_parallel_analysis.zip). In the program I first load an input triangle and duplicate it to have the required number of matrices. Then I start a parallel for loop, where each thread uses cholmod to factorize its matrix. Each thread has its own matrix data, matrix handle, common object, everything is duplicated for each thread. I also set the number fo threads inside cholmod to 1, so only my outer parallelism is emplyed. In the Makefile, change the path to the suitesparse directory, compile with `make` and run with e.g. `./program.x 64 P`.

I compiled SuiteSparse using
```
wget https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/refs/tags/v7.1.0.tar.gz
tar -xf v7.1.0.tar.gz
rm v7.1.0.tar.gz
mv SuiteSparse-7.1.0 SuiteSparse-7.1.0_32_intel
cd SuiteSparse-7.1.0_32_intel
cd SuiteSparse_config
CMAKE_OPTIONS="-DCMAKE_C_COMPILER=icx" make local
make install
cd ..
cd AMD
CMAKE_OPTIONS="-DCMAKE_C_COMPILER=icx" make local
make install
cd ..
cd CAMD
CMAKE_OPTIONS="-DCMAKE_C_COMPILER=icx" make local
make install
cd ..
cd CCOLAMD
CMAKE_OPTIONS="-DCMAKE_C_COMPILER=icx" make local
make install
cd ..
cd COLAMD
CMAKE_OPTIONS="-DCMAKE_C_COMPILER=icx" make local
make install
cd ..
cd CHOLMOD
CMAKE_OPTIONS="-DCMAKE_C_COMPILER=icx -DENABLE_CUDA=false" make local
make install
cd ..
cd ..
cd ..
```

**Expected behavior**
speedup approximately equal to the number of threads (up to memory bandwidth limitation), no race conditions between completely separate cholmod objects

**Screenshots**
![image](https://github.com/DrTimothyAldenDavis/SuiteSparse/assets/91080996/59029fd4-bce5-41ae-91c5-3f2afb4a882b)
![image](https://github.com/DrTimothyAldenDavis/SuiteSparse/assets/91080996/e96f893d-cf01-4a3b-b503-952fb6119c04)

**Desktop (please complete the following information):**
 - OS: CentOS-7
 - compiler icx, icpx 2023.1 (but gcc and g++ and clang produce equivalent behavior)
 - BLAS and LAPACK library: MKL 2023.1 (but AOCL produces equivalent behavior)
 - Version: SuiteSparse 7.1.0

**Additional context**
I am using a 64-core AMD Epyc 7H12 processor.

Is there anything I can do to avoid this issue (except for using AMD/COLAMD or rewriting the `gk_randint64` function part myself)? Is there something I am doing wrong? CHOLMOD *should be* thread-safe when used like this, right? Or is it a bug, and can it please be fixed?

In case I forgot to mention any detail, please ask.

Thanks in advance for help.

**Comment by DrTimothyAldenDavis** [comment] 2023-09-01 22:59
Thanks for the detailed report, and for tracking down the cause.  This is a bug in METIS, but I could see if I can fix it since I don't use any precompiled library (-lmetis). I compile METIS myself so I can make some other changes and then my version won't conflict with any built-in METIS.

The fix is likely very simple.  I could enable the USE_GKRAND option, and then define all of the global state arrays as thread-private.

**Comment by DrTimothyAldenDavis** [comment] 2023-09-01 23:00
I tagged this as an external bug since I'm not the author of METIS.  But I think I can fix my copy of the package, anyway.

**Comment by DrTimothyAldenDavis** [comment] 2023-09-05 01:59
I just made a change to the dev2 branch that I think will fix this.  I'm testing it now.  Can you give it a try?  It should fix the rand issue.  It avoids a global rand state by using the GKRAND random number generator and a threadprivate state.

**Comment by DrTimothyAldenDavis** [comment] 2023-09-05 20:59
I will post SuiteSparse v7.2.0.beta shortly, with CHOLMOD v4.2.0.beta, that should fix this problem.  Let me know if it does, and then I can close this issue.  Thanks again for catching this so I can resolve it.

**Comment by jakub-homola** [comment] 2023-09-05 22:13
Sorry for the delay. I am now on vacation and unable to test it now, I will test it on Monday at the latest. The commit with the fix looks good to me at a first glance.

Thanks a lot 🙂

**Comment by DrTimothyAldenDavis** [comment] 2023-09-05 22:50
No worries.  I will leave the beta release up for as long as it takes for you to check this issue.

**Comment by jakub-homola** [comment] 2023-09-11 09:27
So I just tested it, and it works as expected, the parallel scaling is now approximately linear (with some minor inefficiencies), the problem is fixed. Thanks again

**Comment by DrTimothyAldenDavis** [comment] 2023-09-11 12:46
Great!  Thanks for checking it.  I'll release SuiteSparse v7.2.0 shortly as a stable release.

**Closed as completed by DrTimothyAldenDavis** 2023-09-11 12:46 UTC
Labels: external bug
